swagger: 2.0
info:
  title: FacturalaYA
  version: '1.0'
  description: API para la facturaci贸n electr贸nica de la SUNAT

paths:
  /boleta:
    post:
      summary: Boleta
      tags: []
      responses: {}
      operationId: post-boleta
      description: Generaci贸n de una nueva Boleta electr贸nica
      parameters:
        - schema:
            type: string
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token_cliente:
                  type: string
                ruc_proveedor:
                  type: string
                
                
        description: ''
        
servers:
  - url: 'https://facturalahoy.com/api/facturalaya'
